export const REQUEST_AUTOCOMPLETE_SUCCESS = 'REQUEST_AUTOCOMPLETE_SUCCESS';
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILD = 'REQUEST_FAILD';
export const REQUEST_CITIES = 'REQUEST_CITIES';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_LOCATION_KEY = 'SET_LOCATION_KEY';

