

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const REQUEST_AUTOCOMPLETE_PENDING = 'REQUEST_AUTOCOMPLETE_PENDING';
export const REQUEST_AUTOCOMPLETE_SUCCESS = 'REQUEST_AUTOCOMPLETE_SUCCESS';
export const REQUEST_AUTOCOMPLETE_FAILED = 'REQUEST_AUTOCOMPLETE_FAILED';


export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const TOGGLE_SYMBOL_DEGREE = 'TOGGLE_SYMBOL_DEGREE';
export const SET_LOCATION_KEY = 'SET_LOCATION_KEY';

